[project]
name = 'partage-v1'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ft-trait]
path = 'contracts/ft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.partage-v1]
path = 'contracts/partage-v1.clar'
clarity_version = 1
epoch = 2.0

[contracts.sft-trait]
path = 'contracts/sft-trait.clar'
clarity_version = 1
epoch = 2.0

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
